// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChk2peG0PuVO4Y40o_A8chrZtT0wQHrD8',
    appId: '1:635214651629:web:7a0f116a6abde1bf9e2ce4',
    messagingSenderId: '635214651629',
    projectId: 'seldura-chat-app',
    authDomain: 'seldura-chat-app.firebaseapp.com',
    storageBucket: 'seldura-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByqPsYIPGLUW4ITLtQLd3-X6bVNkfvBbw',
    appId: '1:635214651629:android:17b9ae62bb3200c49e2ce4',
    messagingSenderId: '635214651629',
    projectId: 'seldura-chat-app',
    storageBucket: 'seldura-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb5FxEaBWzuscF0MOsqVwRf0nJ7SWXd70',
    appId: '1:635214651629:ios:1f7723881422528d9e2ce4',
    messagingSenderId: '635214651629',
    projectId: 'seldura-chat-app',
    storageBucket: 'seldura-chat-app.appspot.com',
    iosClientId: '635214651629-jm5ckmbfehmme0c98b1da6vso6clk9n3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
