// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASCJogPKTv1B3GZ121TIeapDnsv7JJAb8',
    appId: '1:626192172396:web:9ab77bc34da270cb361f49',
    messagingSenderId: '626192172396',
    projectId: 'seldura-map-demo',
    authDomain: 'seldura-map-demo.firebaseapp.com',
    storageBucket: 'seldura-map-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwjceS1mgQskURpGqksCyhbvM8XdVfn0',
    appId: '1:626192172396:android:6aecefba5a8f9af0361f49',
    messagingSenderId: '626192172396',
    projectId: 'seldura-map-demo',
    storageBucket: 'seldura-map-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2H4wjtDfM4xjALs7TLmMxnjz8mE-7ZnA',
    appId: '1:626192172396:ios:e878df6d2f32c7ab361f49',
    messagingSenderId: '626192172396',
    projectId: 'seldura-map-demo',
    storageBucket: 'seldura-map-demo.appspot.com',
    iosClientId:
        '626192172396-hk3s4qjvpeb738dl0ql2juvcqos1784h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapsDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2H4wjtDfM4xjALs7TLmMxnjz8mE-7ZnA',
    appId: '1:626192172396:ios:e878df6d2f32c7ab361f49',
    messagingSenderId: '626192172396',
    projectId: 'seldura-map-demo',
    storageBucket: 'seldura-map-demo.appspot.com',
    iosClientId:
        '626192172396-hk3s4qjvpeb738dl0ql2juvcqos1784h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapsDemo',
  );
}
